kind: pipeline
name: gluon-build

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: change site to tdf
  image: docker:git
  commands:
  - cd site
  - git checkout v2018.2-tdf

- name: build-ar71xx-generic
  image: hoffmannhosting/gluon-builder
  volumes:
  - name: gluon
    path: /gluon
  commands:
  - cd /gluon
  - mkdir gdsgklösjd
  - ls /drone/src/gluon
  - make update GLUON_RELEASE=$input_hood-$branch-$input_version -C /drone/src/gluon
  - make -j5 GLUON_BRANCH=$branch GLUON_TARGET=ar71xx-generic GLUON_RELEASE=$input_hood-$branch-$input_version  /drone/src/gluon
  environment:
    branch: stable
    input_hood: tdf
    input_version: v2018.2.2-1
    GLUON_SITEDIR: /drone/src/site

volumes:
- name: gluon
  temp: {}