kind: pipeline
name: gluon-build

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: change site to tdf
  image: docker:git
  commands:
  - cd site
  - git checkout v2019.1-tdf

- name: make update
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make update 
  environment:
    input_hood: tdf
    input_version: v2019.0
    GLUON_SITEDIR: /drone/src/site
    GLUON_TARGET: ar71xx-generic
    FORCE_UNSAFE_CONFIGURE: 1

- name: build-ar71xx-generic
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make -j1 V=s GLUON_BRANCH=experimental GLUON_RELEASE=$input_hood-exp-$input_version GLUON_OUTPUTDIR=output/experimental
  environment:
    input_hood: tdf
    input_version: v2019.0
    GLUON_SITEDIR: /drone/src/site
    GLUON_TARGET: ar71xx-generic
    FORCE_UNSAFE_CONFIGURE: 1

- name: make manifest
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make manifest GLUON_BRANCH=experimental GLUON_OUTPUTDIR=output/experimental GLUON_RELEASE=$input_hood-exp-$input_version
  environment:
    input_hood: tdf
    input_version: v2019.0
    GLUON_SITEDIR: /drone/src/site
    FORCE_UNSAFE_CONFIGURE: 1

- name: upload experimental
  image: appleboy/drone-scp
  settings:
    host: 46.4.138.183
    user: fwupload
    key:
      from_secret: ssh-update
    strip_components: 6
    target: /srv/fwuploads/troisdorf/tdf/experimental
    source: /drone/src/gluon/output/experimental/images/*

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: fftdf_firmware

