kind: pipeline
name: gluon-build

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: change site to multidomain
  image: docker:git
  commands:
  - cd site
  - git checkout testing/v2018.2-multidomain

- name: make update
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make update
  environment:
    input_hood: tdf
    input_version: v2018.2.2-1
    GLUON_SITEDIR: /drone/src/site
    GLUON_BRANCH: stable
    GLUON_TARGET: ar71xx-generic
    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
    FORCE_UNSAFE_CONFIGURE: 1

#- name: build-ar71xx-generic
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ar71xx-generic
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1

- name: build-ar71xx-tiny
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make -j16
  environment:
    input_hood: tdf
    input_version: v2018.2.2-1
    GLUON_SITEDIR: /drone/src/site
    GLUON_BRANCH: stable
    GLUON_TARGET: ar71xx-tiny
    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
    FORCE_UNSAFE_CONFIGURE: 1

#- name: build-ar71xx-nand
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ar71xx-nand
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-brcm2708-bcm2708
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: brcm2708-bcm2708
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-brcm2708-bcm2709
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j1 V=s
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: brcm2708-bcm2709
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-mpc85xx-generic
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: mpc85xx-generic
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-x86-generic
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: x86-generic
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-x86-geode
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: x86-geode
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-x86-64
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: x86-64
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-ipq40xx
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ipq40xx
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-ramips-mt7620
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ramips-mt7620
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-ramips-mt7621
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ramips-mt7621
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-ramips-mt76x8
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ramips-mt76x8
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-ramips-rt305x
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: ramips-rt305x
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1
#
#- name: build-sunxi-cortexa7
#  image: hoffmannhosting/gluon-builder
#  commands:
#  - cd gluon
#  - make -j16
#  environment:
#    input_hood: tdf
#    input_version: v2018.2.2-1
#    GLUON_SITEDIR: /drone/src/site
#    GLUON_BRANCH: stable
#    GLUON_TARGET: sunxi-cortexa7
#    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
#    FORCE_UNSAFE_CONFIGURE: 1

- name: make manifest
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make manifest
  environment:
    input_hood: tdf
    input_version: v2018.2.2-1
    GLUON_SITEDIR: /drone/src/site
    GLUON_BRANCH: stable
    GLUON_TARGET: ramips-rt305x
    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
    FORCE_UNSAFE_CONFIGURE: 1

#- name: backup-old-firmware
#  image: appleboy/drone-ssh
#  settings:
#    host: 46.4.138.183
#    username: fwupload
#    key:
#      from_secret: ssh-update
#    port: 22
#    command_timeout: 120m
#    script:
#      - ./rsync-backup.sh
#      - rm -rf /srv/fwuploads/troisdorf/*

- name: copy-firmware-to-update-server
  image: appleboy/drone-scp
  settings:
    host: 46.4.138.183
    user: fwupload
    key:
      from_secret: ssh-update
    strip_components: 4
    target: /srv/fwuploads/troisdorf/multisite/
    source: /drone/src/gluon/output/*

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: fftdf_firmware
