kind: pipeline
name: gluon-build

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  #- cd gluon
  #- git pull
  #- cd ../site
  #- git pull
  - ls -alh
  - cd gluon
  - git status

- name: build-ar71xx-generic
  image: hoffmannhosting/gluon-builder
  commands:
  - ls -al
  - cd site
  - ls -alh
 # - git checkout v2018.2-tdf
 # - make -j5 GLUON_BRANCH=$branch GLUON_TARGET=ar71xx-generic GLUON_RELEASE=$input_hood-$branch_name-$input_version $gluon_options
  environment:
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
