kind: pipeline
name: gluon-build

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --recursive --init

- name: change site to tdf
  image: docker:git
  commands:
  - cd site
  - git checkout v2018.2-tdf

- name: make update
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make update

- name: build-ar71xx-generic
  image: hoffmannhosting/gluon-builder
  commands:
  - cd gluon
  - make -j16
  environment:
    input_hood: tdf
    input_version: v2018.2.2-1
    GLUON_SITEDIR: /drone/src/site
    GLUON_BRANCH: stable
    GLUON_TARGET: ar71xx-generic
    GLUON_RELEASE: $input_hood-$GLUON_BRANCH-$input_version
    FORCE_UNSAFE_CONFIGURE: 1